sudo: required
services:
    - docker 

before_install:
    - docker build -t kebap/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kebap/react-test npm test

after_success:
    - docker build -t kebap/multi-client ./client
    - docker build -t kebap/multi-nginx ./nginx
    - docker build -t kebap/multi-server ./server
    - docker build -t kebap/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push kebap/multi-client
    - docker push kebap/multi-nginx
    - docker push kebap/multi-server
    - docker push kebap/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-079492886238
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    